({
    baseUrl: "./ftw/colorbox/browser/resources",
    paths: {
        jquery: "empty:",
        jquery_colorbox: "jquery.colorbox-min",
        ftwcolorbox_init: "init-colorbox", // Generated by a view
        ftwcolorbox_additional: "colorbox",
    },
    name: "main",
    out: "./ftw/colorbox/browser/resources/ftw-colorbox-compiled.js"
})
